Apps/Gossip/urls.py
from django.urls import path, re_path
from . import views
from .views import gossips, addGossip, addCharacter

app_name = 'Gossip'

urlpatterns = [
    path('gossips', gossips, name='gossips'),
    path('addGossip', addGossip, name='addgossip'),
    path('addCharacter', addCharacter, name='addCharacter')
    #path('userid', views.userId, name='userId')
]

Apps/Login/urls.py
from django.urls import path, re_path
from . import views
from .views import edit, dashboard, register
from django.urls import reverse_lazy
from django.urls import path, include
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'Login'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='Login/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='Login/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='Login/password_reset_form.html',
        email_template_name='Login/password_reset_email.html',
        success_url=reverse_lazy('Login:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='Login/password_reset_confirm.html',
        success_url=reverse_lazy('Login:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='Login/password_reset_complete.html'), name='password_reset_complete'),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from Apps.Login import views as LoginViews
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('Apps.Login.urls', namespace='Login')),
    path('gossips/', include('Apps.Gossip.urls', namespace='Gossip')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('api-auth/', include('rest_framework.urls')),
]

Apps/Gossip/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from datetime import datetime, timedelta

class Character(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    CharacterName = models.TextField(max_length=500)
    def __str__(self):
        """
        Строка для представления character
        """
        return self.CharacterName
    def __int__(self):
        """
        Получаем id gossip
        """
        return self.id

class Gossip(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    gossipText = models.TextField(max_length=4000)
    pubDate = models.DateTimeField(default=timezone.now)
    EndDate = models.DateTimeField(default=timezone.now)
    characterId = models.ForeignKey(Character, on_delete=models.CASCADE) 
    #interval = models.CharField(max_length=128) можна обійтися без нього
    def __str__(self):
        """
        Строка для представления gossip
        """
        return self.gossipText
    def __int__(self):
        """
        Получаем id gossip
        """
        return self.id
#	def get_absolute_url(self):
#		return reverse('Gossip', args=[str(self.id)])

Apps/Login/models.py
from django.db import models
from django.conf import settings
import json
from django.contrib.auth.models import User

# Create your models here.
class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

Apps/Gossip/forms.py
from django.forms import ModelForm
from .models import Gossip, Character


class Gossipform(ModelForm):
    class Meta:
        model = Gossip
        fields = ['userId','gossipText','pubDate','EndDate','characterId']

class Characterform(ModelForm):
    class Meta:
        model = Character
        fields = ['userId', 'CharacterName']

Apps/Login/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm

class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

Apps/Gossip/views.py
from django.shortcuts import render
from .models import *

from django.http import HttpResponse, Http404
from django.views.generic.base import View
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from .forms import Gossipform, Characterform


# Create your views here.


def gossips(request):
    currentuser = request.user  
    allGossips = Gossip.objects.all().order_by('-pubDate')
    d = []
    gossips = Gossip.objects.values('id').distinct()
    for gossip in allGossips:
        if getattr(gossip, 'userId') == currentuser.id:
            d.append(gossip['id'])
    userGossips = Gossip.objects.all().filter(id__in=d).order_by('-pubDate')


    context = {
        "allGossips" : allGossips,
        "userGossips" : userGossips,
        "user" : currentuser,
    }
    return render(request, 'gossips.html', context)
def addGossip(request):
    if request.method == 'POST':
        form = Gossipform(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = Gossipform()
    context = {
        'form': form,
    }
    return render(request, 'addgossip.html', context=context)
def addCharacter(request):
    if request.method == 'POST':
        form = Characterform(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = Characterform()
    context = {
        'form': form,
    }
    return render(request, 'addCharacter.html', context=context)

Apps/Login/views.py
from django.http import request
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm


# Create your views here.

@login_required
def dashboard(request):
    context = {
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'dashboard.html', context=context)


def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'register.html', context=context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'edit.html', context=context)

Apps/Gossip/templates/addCharacter.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Registration

{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Apps/Gossip/templates/addgossip.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Registration

{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Apps/Gossip/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    
        <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>App {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

    
</body>

</html>

Apps/Gossip/templates/gossips.html
{% extends "base.html" %}
{% block title %}Gossips{% endblock title %}
{% block content %}
<h1>{{welcome}}</h1>
<br>
    <p>Hello, {{user}}</p>
    <p>All gossips are:</p>
    {% for gossip in allGossips %}
    <p>{{gossip.characterId}}</p>
    <ul>
        <li>" {{gossip.gossipText}} "</li>
        <br>
    </ul>
    {% endfor %}
<hr>
{% endblock content %}

Apps/Gossip/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">gossipRecs <i class="fas fa-boxes"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Login:dashboard' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">All Gossips</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Character</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Add Gossip</a>
            </li>
        </ul>
        {% endif %}
        <span>
            {% if request.user.is_authenticated %}
            <a href="{% url 'Login:logout' %}" class="btn btn-danger">Logout</a>
            Hello
            @ <i>{{user.username}}</i>
            {% else %}
            <div class="login__left">
                <a href="{% url 'Login:login' %}" class="btn btn-secondary">Log-in</a>
                <a href="{% url 'Login:register' %}" class="btn btn-info ">Register</a>
            </div>

            {% endif %}

        </span>
    </div>
</nav>

Apps/Login/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    
        <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>App {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    
</body>

</html>

Apps/Login/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock title %}
<style>
    body {
      background-image: url('static/css/main.jpg');
      background-repeat: no-repeat;
    }
    </style>
{% block content %}
<h1>{{welcome}}</h1>
<br>
<a href="{% url 'Login:edit' %}" class="btn btn-primary">Edit Your Profile</a> or
<a href="{% url 'Login:password_change' %}" class="btn btn-warning">Change your password</a>
<hr>
{% endblock content %}

Apps/Login/templates/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Apps/Login/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}

{% endblock content %}

Apps/Login/templates/logged_out.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
<h1>Logged out</h1>
<p>
    You have been successfully logged out.
    <hr>
    You can <a href="{% url 'Login:login' %}">log-in again</a>.
</p>
{% endblock %}

Apps/Login/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Login{% endblock title %}

{% block content %}
<div class="">
    <div style="text-align: center;">
        <h1>Log-in</h1>
        {% if form.errors %}
        <p>
            Your username and password didn't match.Please
            Please try again.
        </p>
        {% else %}
        <p>Please, use the following form to log-in</p>
        {% endif %}
    </div>

    <form action="" method="post" class="form ">
        <p><a href="{% url 'Login:password_reset' %}">Forgotten your password?</a></p>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <input type="hidden" name="next" value="{{ next }}" />
        <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
    <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
    <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
    <a href="{% url 'social:begin' backend='google-oauth2' %}">Login with Google</a>
</div>
{% endblock content %}

Apps/Login/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">gossipRecs <i class="fas fa-boxes"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Login:dashboard' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Gossip:gossips' %}">All Gossips</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Gossip:addCharacter' %}">Add Character</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'Gossip:addgossip' %}">Add Gossip</a>
            </li>
        </ul>
        {% endif %}
        <span>
            {% if request.user.is_authenticated %}
            <a href="{% url 'Login:logout' %}" class="btn btn-danger">Logout</a>
            Hello
            @ <i>{{user.username}}</i>
            {% else %}
            <div class="login__left">
                <a href="{% url 'Login:login' %}" class="btn btn-secondary">Log-in</a>
                <a href="{% url 'Login:register' %}" class="btn btn-info ">Register</a>
            </div>

            {% endif %}

        </span>
    </div>
</nav>

Apps/Login/templates/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Change Your Password</h2>
<p>Use the form below to change your Password</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Apps/Login/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" value="Change my password">Submit</button>
    {% endbuttons %}
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
    already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

Apps/Login/templates/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered
    the address you registered with.</p>
{% endblock %}

Apps/Login/templates/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below
{{ protocol }}://{{ domain }}{% url "Login:password_reset_confirm"
uidb64=uid token=token %}

Apps/Login/templates/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Reset your password

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Forgotten your Password</h2>
    <p>Enter your email address to obtain a new password</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary" value="send e-mail">Submit</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

Apps/Login/templates/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Registration

{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

Apps/Login/templates/register_done.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url 'Login:login' %}">log in</a>.</p>
{% endblock content %}

mysite/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    
        <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>App {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

    
</body>

</html>

mysite/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}

{% endblock content %}

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">Authentication <i class="fas fa-boxes"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Dashboard</a>
            </li>
        </ul>
        {% endif %}
        <span>
            {% if request.user.is_authenticated %}
            <a href="{% url 'Login:logout' %}" class="btn btn-danger">Logout</a>
            Hello
            @ <i>{{user.username}}</i>
            {% else %}
            <div class="login__left">
                <a href="{% url 'Login:login' %}" class="btn btn-secondary">Log-in</a>
                <a href="{% url 'Login:register' %}" class="btn btn-info ">Register</a>
            </div>

            {% endif %}

        </span>
    </div>
</nav>